### ISSUE TITLE
Installation of 0.5 fails with syntaxError, 0.4 installs without error.

### ISSUE THREAD

**Issue by ddwagner** [nipy/heudiconv#180]
Tried upgrading to 0.5 via pip and am getting the following error.

```
Processing ./heudiconv-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-6L_OZR-build/setup.py", line 22
        exec(infofile.read(), globals(), ldict)
    SyntaxError: unqualified exec is not allowed in function 'main' it contains a nested function with free variables
```
My intuition is that this is a Python version issue with the older 2.7s.  I get this error on Ubuntu and Linux Mint (both trusty) with python 2.7.5 (highest available). Installing heudiconv 0.5 in a Xenial VM with Python 2.7.12 appears to work fine so far. 

I'll be upgrading my Ubuntu trusty servers soon as Beaver LTS comes out but in the meantime, there's still a year+ on the clock for Trusty. 

Thanks.

**Comment by yarikoptic** [comment]
According to http://neuro.debian.net/pkgs/heudiconv.html we provide a build for trusty so you could just install it. For that to happen we have a patch for elderly pythons: https://github.com/nipy/heudiconv/blob/debian/debian/patches/deb_old_python2
which IIRC cannot really be incorporated into the code since it uses old syntax which would trigger failures on newer Pythons. so if you run older one -- just patch manually or install from NeuroDebian

**Comment by ddwagner** [comment]
Late to respond, but thanks. The neurodebian release works great. A bit worried about conflicts with my pip installs but so far so good.
