### ISSUE TITLE
TraitError: The 'source_dir' trait of a Dcm2niixInputSpec instance must be an existing directory name

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#184]
With fresh nipype 1.0.2 (I believe) we started getting tests failures  as e.g. in #183
```
trait_notifiers.py         238 ERROR    Exception occurred in traits notification handler for object: 
anon_bids = <undefined>
args = <undefined>
bids_format = True
comment = <undefined>
compress = y
compression = <undefined>
crop = False
environ = {}
has_private = False
ignore_deriv = <undefined>
ignore_exception = False
merge_imgs = False
out_filename = <undefined>
output_dir = .
philips_float = <undefined>
series_numbers = <undefined>
single_file = False
source_dir = <undefined>
source_names = <undefined>
terminal_output = <undefined>
verbose = False
, trait: source_names, old value: <undefined>, new value: [u'/home/travis/build/nipy/heudiconv/tests/data/01-fmap_acq-3mm/1.3.12.2.1107.5.2.43.66112.2016101409263663466202201.dcm']
Traceback (most recent call last):
  File "/home/travis/build/nipy/heudiconv/venv/lib/python2.7/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/travis/build/nipy/heudiconv/venv/lib/python2.7/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/home/travis/build/nipy/heudiconv/venv/lib/python2.7/site-packages/nipype/interfaces/base/specs.py", line 151, in _deprecated_warn
    '%s' % trait_spec.new_name: new
  File "/home/travis/build/nipy/heudiconv/venv/lib/python2.7/site-packages/traits/has_traits.py", line 1539, in trait_set
    setattr( self, name, value )
  File "/home/travis/build/nipy/heudiconv/venv/lib/python2.7/site-packages/nipype/interfaces/base/traits_extension.py", line 175, in validate
    self.error(object, name, value)
  File "/home/travis/build/nipy/heudiconv/venv/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
TraitError: The 'source_dir' trait of a Dcm2niixInputSpec instance must be an existing directory name, but a value of [u'/home/travis/build/nipy/heudiconv/tests/data/01-fmap_acq-3mm/1.3.12.2.1107.5.2.43.66112.2016101409263663466202201.dcm'] <class 'traits.trait_handlers.TraitListObject'> was specified.
```

@satra @effigies @mgxd - could you please have a look?

**Comment by mgxd** [comment]
@yarikoptic looks like we need to specify the directory within heudiconv, instead of the full path

`/home/travis/build/nipy/heudiconv/tests/data/01-fmap_acq-3mm/`

**Comment by sjburwell** [comment]
I started getting two classes of errors with the installation (I think) of first nipype 1.0.1, and then a different sort of error with nipype 1.0.2

**Command:**
heudiconv -d /labs/burwellstudy/data/fmri/20180403_cotdata/{subject}/*/* \
          -s 8143471 \
          -c dcm2niix \
          -f /labs/burwellstudy/projects/nipype2/bids_conversion/myheuristics/cot_v2p0_heuristic.py \
          -b --overwrite \
          -o /labs/burwellstudy/data/fmri/20180403_cotdata_bids

**Error with nipype 1.0.1**
...
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'session': None, 'outdir': '/labs/burwellstudy/data/fmri/20180403_cotdata_bids/', 'subject': '8143471'}
INFO: Processing 2415 dicoms
INFO: Analyzing 2415 dicoms
INFO: Generated sequence info with 18 entries
INFO: Doing conversion using dcm2niix
INFO: Converting /labs/burwellstudy/data/fmri/20180403_cotdata_bids/sub-8143471/ses-00/dwi/sub-8143471_ses-00_run-01_dwi (63 DICOMs) -> /labs/burwellstudy/data/fmri/20180403_cotdata_bids/sub-8143471/ses-00/dwi . Converter: dcm2niix . Output types: ['nii.gz']
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: 
...
Traceback (most recent call last):
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/nipype/interfaces/base/specs.py", line 140, in _deprecated_warn
    raise TraitError(msg)
TraitError: Input terminal_output in interface Dcm2niix is deprecated. Will be removed or raise an error as of release 1.0.0 
Traceback (most recent call last):
  File "/labs/burwellstudy/projects/nipype2/bin/heudiconv", line 2197, in <module>
    main()
  File "/labs/burwellstudy/projects/nipype2/bin/heudiconv", line 2189, in main
    return _main(args)
  File "/labs/burwellstudy/projects/nipype2/bin/heudiconv", line 2052, in _main
    min_meta=args.minmeta)
  File "/labs/burwellstudy/projects/nipype2/bin/heudiconv", line 1407, in convert_dicoms
    min_meta=min_meta)
  File "/labs/burwellstudy/projects/nipype2/bin/heudiconv", line 910, in convert
    convertnode.inputs.terminal_output = 'allatonce'
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 474, in __call__
    self.notify_listener( self, object, trait_name, old, new )
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 545, in _notify_method_listener
    listener )
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 526, in _dispatch_change_event
    handle_exception( object, trait_name, old, new )
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/nipype/interfaces/base/specs.py", line 140, in _deprecated_warn
    raise TraitError(msg)
traits.trait_errors.TraitError: Input terminal_output in interface Dcm2niix is deprecated. Will be removed or raise an error as of release 1.0.0 

**Error with nipype 1.0.2**
...
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'session': None, 'outdir': '/labs/burwellstudy/data/fmri/20180403_cotdata_bids/', 'subject': '8143471'}
INFO: Processing 2415 dicoms
INFO: Reloading existing filegroup.json because /labs/burwellstudy/data/fmri/20180403_cotdata_bids/.heudiconv/8143471/info/8143471.edit.txt exists
INFO: Doing conversion using dcm2niix
INFO: Converting /labs/burwellstudy/data/fmri/20180403_cotdata_bids/sub-8143471/anat/sub-8143471_run-01_T1w (240 DICOMs) -> /labs/burwellstudy/data/fmri/20180403_cotdata_bids/sub-8143471/anat . Converter: dcm2niix . Output types: ['nii.gz']
/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/nipype/interfaces/base/specs.py:145: UserWarning: Input source_names in interface Dcm2niix is deprecated. Will be removed or raise an error as of release 1.0.2 It has been replaced by source_dir.Unsetting old value source_names; setting new value source_dir.
  warn(msg)
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: 
...
Traceback (most recent call last):
  File "/labs/burwellstudy/projects/nipype2/bin/heudiconv", line 2197, in <module>
    main()
  File "/labs/burwellstudy/projects/nipype2/bin/heudiconv", line 2189, in main
    return _main(args)
  File "/labs/burwellstudy/projects/nipype2/bin/heudiconv", line 2052, in _main
    min_meta=args.minmeta)
  File "/labs/burwellstudy/projects/nipype2/bin/heudiconv", line 1407, in convert_dicoms
    min_meta=min_meta)
  File "/labs/burwellstudy/projects/nipype2/bin/heudiconv", line 903, in convert
    convertnode.inputs.source_names = item_dicoms
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 474, in __call__
    self.notify_listener( self, object, trait_name, old, new )
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 545, in _notify_method_listener
    listener )
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 526, in _dispatch_change_event
    handle_exception( object, trait_name, old, new )
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/nipype/interfaces/base/specs.py", line 151, in _deprecated_warn
    '%s' % trait_spec.new_name: new
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/has_traits.py", line 1539, in trait_set
    setattr( self, name, value )
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/nipype/interfaces/base/traits_extension.py", line 175, in validate
    self.error(object, name, value)
  File "/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'source_dir' trait of a Dcm2niixInputSpec instance must be an existing directory name, but a value of [u'/labs/burwellstudy/data/fmri/20180403_cotdata/8143471/PN-COT81434_71-ST001-SE003-CoT_B_T1_MPRAGE_Cor_GR2/PN-COT81434_71-ST001-SE003-0001.dcm', u'/labs/burwellstudy/data/fmri/20180403_cotdata/8143471/PN-COT81434_71-ST001-SE003-CoT_B_T1_MPRAGE_Cor_GR2/PN-COT81434_71-ST001-SE003-0002.dcm', ..., u'/labs/burwellstudy/data/fmri/20180403_cotdata/8143471/PN-COT81434_71-ST001-SE003-CoT_B_T1_MPRAGE_Cor_GR2/PN-COT81434_71-ST001-SE003-0240.dcm'] <class 'traits.trait_handlers.TraitListObject'> was specified.

Any thoughts on how my heudiconv command may be altered to resolve this issue? The heuristics file worked on previous versions of nipype.

**Comment by sjburwell** [comment]
I think I originally upgraded (which gave me the previously reported errors) using: pip install heudiconv --upgrade

Although, I'm not certain installing from the git master is working as it should:
[nipype2] burwell@lts:/labs/burwellstudy/projects/nipype2 13% pip install https://github.com/nipy/heudiconv/archive/master.zip
Collecting https://github.com/nipy/heudiconv/archive/master.zip
  Downloading https://github.com/nipy/heudiconv/archive/master.zip
     \ 143kB 2.5MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-NKNQvX-build/setup.py", line 22
        exec(infofile.read(), globals(), ldict)
    SyntaxError: unqualified exec is not allowed in function 'main' it contains a nested function with free variables
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-NKNQvX-build/

**Comment by butellyn** [comment]
I am using a singularity image of [heudiconv 0.9.0 from Dockerhub](https://hub.docker.com/layers/nipy/heudiconv/0.9.0/images/sha256-42a4ab94a4af122e1031648f28dbc40a05b8b6cd6e720c7e94e539e93a519636?context=explore), and am getting the same error. Has this issue been fixed in heudiconv 0.9.0? Here is my call:

```
singularity run --writable-tmpfs --cleanenv \
  -B /projects/b1108/studies/mwmh:/base \
  /home/erb9722/heudiconv_0.9.0.sif \
  -d /base/data/raw/neuroimaging/dicoms/sub-{subject}/*/*/*/*/*.dcm \
  -o /base/data/raw/neuroimaging/bids/ \
  -f /base/scripts/curation/heuristic.py -s MWMH219 -c dcm2niix -b --overwrite
```

**Comment by yarikoptic** [comment]
Eh, @mgxd do you have any recollection why/how you closed this issue?

Having said that, I haven't seen this issue for long time. @butellyn , do you have full traceback? I don't see you using option to not bind HOME - could you use it with empty HOME bound? Do you see the same error using 0.9.0 image from http://datasets.datalad.org/?dir=/repronim/containers/images/repronim

**Comment by butellyn** [comment]
Yes, see the full traceback below. It isn't identical to the example, but they both have an issue with `source_names`. Not sure what this means. What do you mean by an "empty HOME bound"? Should I just bind my home directory as follows: `-B /home/erb9722`? I have to install datalad, but I'll let you know.

```
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 33, in <module>
    sys.exit(load_entry_point('heudiconv', 'console_scripts', 'heudiconv')())
  File "/src/heudiconv/heudiconv/cli/run.py", line 24, in main
    workflow(**kwargs)
  File "/src/heudiconv/heudiconv/main.py", line 351, in workflow
    grouping=grouping,)
  File "/src/heudiconv/heudiconv/convert.py", line 216, in prep_conversion
    dcmconfig=dcmconfig,)
  File "/src/heudiconv/heudiconv/convert.py", line 476, in convert
    bids_options, tmpdir, dcmconfig)
  File "/src/heudiconv/heudiconv/convert.py", line 618, in nipype_convert
    convertnode.inputs.source_names = item_dicoms
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 426, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_types.py", line 2473, in validate
    return TraitListObject(self, object, name, value)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 582, in __init__
    notifiers=[self.notifier],
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 210, in __init__
    super().__init__(self.item_validator(item) for item in iterable)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 210, in <genexpr>
    super().__init__(self.item_validator(item) for item in iterable)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 862, in _item_validator
    return trait_validator(object, self.name, value)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/base_trait_handler.py", line 75, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: Each element of the 'source_names' trait of a Dcm2niixInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/base/dicoms/sub-MWMH219/ses-1/SCANS/1/DICOM/MWMH219.MR.fMRI_STUDIES_MILLER.1.1.20160601.091443.v9f0wy.dcm' <class 'str'> was specified.
```

**Comment by yarikoptic** [comment]
> What do you mean by an "empty HOME bound"?

probably never mind that since from traceback I see that it is not some rogue nipype from `~/.local`

> I have to install datalad, but I'll let you know.

sorry for being not descriptive enough -- no need to install datalad (although always encouraged), just click on that image in that page and download that http://datasets.datalad.org/repronim/containers/images/repronim/repronim-reproin--0.9.0.sing .   But the question is whether you do have `/base/dicoms/sub-MWMH219/ses-1/SCANS/1/DICOM/MWMH219.MR.fMRI_STUDIES_MILLER.1.1.20160601.091443.v9f0wy.dcm` with data (may be it is under datalad and not yet downloaded/broken link) which outside is   `/projects/b1108/studies/mwmh/dicoms/sub-MWMH219/ses-1/SCANS/1/DICOM/MWMH219.MR.fMRI_STUDIES_MILLER.1.1.20160601.091443.v9f0wy.dcm` I guess

**Comment by butellyn** [comment]
Oh, odd. So the file exists here outside the container: `/projects/b1108/studies/mwmh/data/raw/neuroimaging/dicoms/sub-MWMH219/ses-1/SCANS/1/DICOM/MWMH219.MR.fMRI_STUDIES_MILLER.1.1.20160601.091443.v9f0wy.dcm`. I am not sre why the `data/raw/neuroimaging` directories aren't there. Did I mess something up with my bind?

**Comment by yarikoptic** [comment]
any symlinks involved along the path, i.e. is `/projects/b1108/studies/mwmh/data/raw/neuroimaging` may be a symlink?  I would run smth like
```
$> p=$PWD ; while [ "$p" != "/" ]; do ls -ld $p; p=$(dirname $p); done
drwxr-s--- 1 yoh yoh 17486 Mar  2 13:21 /home/yoh/
drwxr-xr-x 1 root root 228 Aug 26  2021 /home/
```
on that path and see if nothing is a curious symlink

**Comment by butellyn** [comment]
Hm, I don't see why it would be. I created all of the directories after `/projects/b1108/`. Here is the output I got after running that command:

```
drwxrws---+ 5 erb9722 b1108 16384 Feb 17 21:16 /projects/b1108/studies/mwmh/data/raw/neuroimaging
drwxrws---+ 6 erb9722 b1108 4096 Feb  1 14:32 /projects/b1108/studies/mwmh/data/raw
drwxrws---+ 4 erb9722 b1108 4096 Feb  1 14:32 /projects/b1108/studies/mwmh/data
drwxrws---+ 13 erb9722 b1108 4096 Mar  1 15:42 /projects/b1108/studies/mwmh
drwxrws---+ 8 erb9722 b1108 4096 Jan 31 21:27 /projects/b1108/studies
drwxrws---+ 13 root b1108 32768 Feb 25 21:34 /projects/b1108
drwxr-xr-x 1273 root root 262144 Mar  2 13:34 /projects
```

**Comment by yarikoptic** [comment]
I would have tried to enter bash inside and see "first hand" either that path or what along the way exists or not etc

```
singularity exec --writable-tmpfs --cleanenv \
  -B /projects/b1108/studies/mwmh:/base \
  /home/erb9722/heudiconv_0.9.0.sif bash \
  -d /base/data/raw/neuroimaging/dicoms/sub-{subject}/*/*/*/*/*.dcm \
  -o /base/data/raw/neuroimaging/bids/ \
  -f /base/scripts/curation/heuristic.py -s MWMH219 -c dcm2niix -b --overwrite
```

**Comment by butellyn** [comment]
Just went into the container and `/base/dicoms/sub-MWMH219/ses-1/SCANS/1/DICOM/MWMH219.MR.fMRI_STUDIES_MILLER.1.1.20160601.091443.v9f0wy.dcm` does not exist there, but `/base/data/raw/neuroimaging/dicoms/sub-MWMH219/ses-1/SCANS/1/DICOM/MWMH219.MR.fMRI_STUDIES_MILLER.1.1.20160601.091443.v9f0wy.dcm` does. So I guess the question is, why does heudiconv think the former file should exist?

**Comment by crcox** [comment]
I think I am having a flavor of the same issue. I get the same error more quickly if I try to use the `--dicom_dir_template`.

Command:

```
podman run \
  --rm \
  --user root \
  --volume ${PWD}/DICOM/:/data:Z \
  --volume ${PWD}/Nifti/:/output:Z \
  --tmpfs=/run \
  --tmpfs=/tmp \
  docker.io/nipy/heudiconv:latest \
    --files \
      /data/crcox/Ser3 \
      /data/crcox/Ser4 \
    --subjects "crcox" \
    --outdir /output \
    --heuristic /output/code/heuristic.py \
    --converter dcm2niix \
    --overwrite \
    --bids
```

Output:
```
[chriscox@relearn0 MRS_fMRI_16Feb2022_MultiEcho]$ ./02_dicom_to_bids.sh
INFO: Running heudiconv version 0.9.0 latest 0.10.0
INFO: Analyzing 13424 dicoms
INFO: Generated sequence info for 1 studies with 2 entries total
WARNING: Heuristic is missing an `infotoids` method, assigning empty method and using provided subject id crcox. Provide `session` and `locator` fields for best results.
INFO: Study session for StudySessionInfo(locator=None, session=None, subject='crcox')
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'subject': 'crcox', 'outdir': '/output/', 'session': None}
INFO: Processing 2 pre-sorted seqinfo entries
INFO: Reloading existing filegroup.json because /output/.heudiconv/crcox/info/crcox.edit.txt exists
INFO: Doing conversion using dcm2niix
INFO: Converting /output/run001 (30 DICOMs) -> /output . Converter: dcm2niix . Output types: ('nii.gz',)
220328-21:22:01,683 nipype.utils WARNING:
         A newer version (1.7.0) of nipy/nipype is available. You are using 1.6.0
WARNING: A newer version (1.7.0) of nipy/nipype is available. You are using 1.6.0
220328-21:22:01,685 nipype.workflow INFO:
         [Node] Setting-up "convert" in "/tmp/dcm2niixgqigrzyl/convert".
INFO: [Node] Setting-up "convert" in "/tmp/dcm2niixgqigrzyl/convert".
220328-21:22:01,697 nipype.workflow INFO:
         [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z y -x n -t n -m n -f run001_heudiconv257 -o /output -s n -v n /tmp/dcm2niixgqigrzyl/convert
INFO: [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z y -x n -t n -m n -f run001_heudiconv257 -o /output -s n -v n /tmp/dcm2niixgqigrzyl/convert
220328-21:22:01,792 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.792619:Chris Rorden's dcm2niiX version v1.0.20190410  GCC6.3.0 (64-bit Linux)
INFO: stdout 2022-03-28T21:22:01.792619:Chris Rorden's dcm2niiX version v1.0.20190410  GCC6.3.0 (64-bit Linux)
220328-21:22:01,793 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.792619:Found 30 DICOM file(s)
INFO: stdout 2022-03-28T21:22:01.792619:Found 30 DICOM file(s)
220328-21:22:01,793 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.792619:slices not stacked: orientation varies (vNav or localizer?) [1 -0 0 -0 -0 -1] != [-0 1 0 -0 -0 -1]
INFO: stdout 2022-03-28T21:22:01.792619:slices not stacked: orientation varies (vNav or localizer?) [1 -0 0 -0 -0 -1] != [-0 1 0 -0 -0 -1]
220328-21:22:01,793 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.792619:Convert 10 DICOM as /output/run001_heudiconv257_i00021 (256x256x10x1)
INFO: stdout 2022-03-28T21:22:01.792619:Convert 10 DICOM as /output/run001_heudiconv257_i00021 (256x256x10x1)
220328-21:22:01,891 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.891007:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run001_heudiconv257_i00021.nii"
INFO: stdout 2022-03-28T21:22:01.891007:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run001_heudiconv257_i00021.nii"
INFO: stdout 2022-03-28T21:22:01.891007:Convert 10 DICOM as /output/run001_heudiconv257_i00011 (256x256x10x1)
220328-21:22:01,891 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.891007:Convert 10 DICOM as /output/run001_heudiconv257_i00011 (256x256x10x1)
220328-21:22:01,984 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.984006:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run001_heudiconv257_i00011.nii"
INFO: stdout 2022-03-28T21:22:01.984006:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run001_heudiconv257_i00011.nii"
INFO: stdout 2022-03-28T21:22:01.984006:Convert 10 DICOM as /output/run001_heudiconv257_i00001 (256x256x10x1)
220328-21:22:01,984 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.984006:Convert 10 DICOM as /output/run001_heudiconv257_i00001 (256x256x10x1)
220328-21:22:02,77 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.077853:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run001_heudiconv257_i00001.nii"
INFO: stdout 2022-03-28T21:22:02.077853:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run001_heudiconv257_i00001.nii"
220328-21:22:02,78 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.077853:Conversion required 0.305899 seconds (0.028072 for core code).
INFO: stdout 2022-03-28T21:22:02.077853:Conversion required 0.305899 seconds (0.028072 for core code).
220328-21:22:02,111 nipype.workflow INFO:
         [Node] Finished "convert".
INFO: [Node] Finished "convert".
WARNING: Failed to detect fullfilled BIDS layout.  No scans.tsv file(s) will be produced for /output/run0011.json, /output/run0012.json, /output/run0013.json
WARNING: Failed to find task field in /output/run0011.json.
WARNING: Failed to find task field in /output/run0012.json.
WARNING: Failed to find task field in /output/run0013.json.
WARNING: For now not embedding BIDS and info generated .nii.gz itself since sequence produced multiple files
INFO: Converting /output/run002 (176 DICOMs) -> /output . Converter: dcm2niix . Output types: ('nii.gz',)
220328-21:22:02,133 nipype.workflow INFO:
         [Node] Setting-up "convert" in "/tmp/dcm2niixcrj69ysh/convert".
INFO: [Node] Setting-up "convert" in "/tmp/dcm2niixcrj69ysh/convert".
220328-21:22:02,181 nipype.workflow INFO:
         [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z y -x n -t n -m n -f run002_heudiconv409 -o /output -s n -v n /tmp/dcm2niixcrj69ysh/convert
INFO: [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z y -x n -t n -m n -f run002_heudiconv409 -o /output -s n -v n /tmp/dcm2niixcrj69ysh/convert
220328-21:22:02,298 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.298862:Chris Rorden's dcm2niiX version v1.0.20190410  GCC6.3.0 (64-bit Linux)
INFO: stdout 2022-03-28T21:22:02.298862:Chris Rorden's dcm2niiX version v1.0.20190410  GCC6.3.0 (64-bit Linux)
220328-21:22:02,299 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.298862:Found 176 DICOM file(s)
INFO: stdout 2022-03-28T21:22:02.298862:Found 176 DICOM file(s)
220328-21:22:02,299 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.298862:Convert 176 DICOM as /output/run002_heudiconv409 (256x256x176x1)
INFO: stdout 2022-03-28T21:22:02.298862:Convert 176 DICOM as /output/run002_heudiconv409 (256x256x176x1)
220328-21:22:02,891 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.891219:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run002_heudiconv409.nii"
INFO: stdout 2022-03-28T21:22:02.891219:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run002_heudiconv409.nii"
220328-21:22:02,891 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.891219:Conversion required 0.690064 seconds (0.586886 for core code).
INFO: stdout 2022-03-28T21:22:02.891219:Conversion required 0.690064 seconds (0.586886 for core code).
220328-21:22:02,927 nipype.workflow INFO:
         [Node] Finished "convert".
INFO: [Node] Finished "convert".
WARNING: Failed to detect fullfilled BIDS layout.  No scans.tsv file(s) will be produced for /output/run002.json
WARNING: Failed to find task field in /output/run002.json.
220328-21:22:02,952 nipype.workflow INFO:
         [Node] Setting-up "embedder" in "/tmp/embedmetahl3wg4bz/embedder".
INFO: [Node] Setting-up "embedder" in "/tmp/embedmetahl3wg4bz/embedder".
220328-21:22:02,968 nipype.workflow INFO:
         [Node] Running "embedder" ("nipype.interfaces.utility.wrappers.Function")
INFO: [Node] Running "embedder" ("nipype.interfaces.utility.wrappers.Function")
220328-21:22:09,176 nipype.workflow INFO:
         [Node] Finished "embedder".
INFO: [Node] Finished "embedder".
INFO: Post-treating /output/run002.json file
INFO: Converting /output/run003 (13248 DICOMs) -> /output . Converter: dcm2niix . Output types: ('nii.gz',)
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 33, in <module>
    sys.exit(load_entry_point('heudiconv', 'console_scripts', 'heudiconv')())
  File "/src/heudiconv/heudiconv/cli/run.py", line 24, in main
    workflow(**kwargs)
  File "/src/heudiconv/heudiconv/main.py", line 351, in workflow
    grouping=grouping,)
  File "/src/heudiconv/heudiconv/convert.py", line 216, in prep_conversion
    dcmconfig=dcmconfig,)
  File "/src/heudiconv/heudiconv/convert.py", line 476, in convert
    bids_options, tmpdir, dcmconfig)
  File "/src/heudiconv/heudiconv/convert.py", line 618, in nipype_convert
    convertnode.inputs.source_names = item_dicoms
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 426, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_types.py", line 2473, in validate
    return TraitListObject(self, object, name, value)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 582, in __init__
    notifiers=[self.notifier],
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 210, in __init__
    super().__init__(self.item_validator(item) for item in iterable)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 210, in <genexpr>
    super().__init__(self.item_validator(item) for item in iterable)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 862, in _item_validator
    return trait_validator(object, self.name, value)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/base_trait_handler.py", line 75, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: Each element of the 'source_names' trait of a Dcm2niixInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/data/crcox/Ser4/i6191681.MRDC.2' <class 'str'> was specified.

```

**Comment by yarikoptic** [comment]
FTR: @crcox  filed a dedicated issue https://github.com/nipy/heudiconv/issues/184 for that, so let's continue there!

**Comment by butellyn** [comment]
Sorry, #184 is this issue. Did you mean tag another one?

**Comment by yarikoptic** [comment]
;-) correct -- #550 -- thank you @butellyn !  Fixing original post
