### ISSUE TITLE
json file does not contain the information that dcmstack outputs 

### ISSUE THREAD

**Issue by argyelan** [nipy/heudiconv#258]
I used the dockerized version of heudiconv to convert dicom (Siemens Prisma) to BIDS a year ago. Recently I tried to use it again with newer version of nipy/heudiconv, however the json file was not containing the same information. (I can't use my older version of image because it did not recognize series_id, which is in my new heuristic file)
My main problem is that I would need the metatag: CsaImage.RealDwellTime which is an output of the dcmstack, and is created correctly if i run it inside the container dcmstack --dest-dir ./ -d --embed-meta dicomdir, but when I run the heudiconv it does not append the same info in json file under global. 
Is there an easy fix?

**Comment by chrisfilo** [comment]
I'm not sure what is the status of embedding metadata extracted with dcmstack, but the metadata you are looking for is now part of BIDS and should be harmonized by dcm2niix (used by heudiconv internally) across different scanners (see TotalReadoutTime and EffectiveEcho spacing http://bids.neuroimaging.io/bids_spec.pdf).

**Comment by yarikoptic** [comment]
yeah, dcm2niix level would be the best. in heudiconv we started to strip away all Csa* fields since it was too many to manage: https://github.com/nipy/heudiconv/blob/be86828c866661aa62caadd703f03d33d5bf97b2/heudiconv/utils.py#L236
BUT, boiling down again to be able to configure various stages in heudiconv, might be nice to make explicit whitelist just in case (although again -- harmonization by dcm2niix would be a better way out)

**Comment by satra** [comment]
the flag `--minmeta` may be turned on by default - but that's what helped control

**Comment by argyelan** [comment]
You are right I probably do not even need Csa metas anymore. Thanks, your package is a great help by the way!
