### ISSUE TITLE
rationale behind seqinfo structure

### ISSUE THREAD

**Issue by bpinsard** [nipy/heudiconv#312]
I am trying to use heudiconv to convert all the data from one scanner to bids.
I like the fact that we have access to the full power of python to write complex heuristics but the seqinfo given to infotodict is missing a lot of information from the dicoms that would really help identify runs without relying on fields that can be modified at the console like SeriesDescription or else.

For instance, I would rather get the phase encoding direction from a specific field than from the string '_AP' being included in the SeriesDescription.
The same problem occurs for the infotoids.

Is there a reason to make the seqinfo that sparse?
Are there any plans to provide extension?
What are the 'unspecified2' 'unspecified3' field for?

Thanks!

**Comment by satra** [comment]
@bpinsard - at this point one could really extend sequence info to probably all dicom tags (except for size and storage). the initial version was based on dicomconvert from freesurfer (and that's where unspecified2/3 also come from.  that conformance is no longer required. however, for backwards compatibility, we would want to keep the existing keys even if we add a lot more metadata. the dicominfo.tsv file should also not increase in size. usually these keys are sufficient to do many conversions instead of bloating up seqinfo with all the dicom metadata.

perhaps one of two things could happen:
1. one is a list of dicom tags that could be included can be specified as a flag to heudiconv or via a tuple in the heuristic file. or

2. add an example dicom object for each item as an additional field to the sequence_info. since this would be based on pydicom, the heuristic could use any dicom tag to take a decision.

**Comment by bpinsard** [comment]
@satra Thanks for the quick reply.
I didn't know that the structure was inherited from mri_convert.

Both options would be great, maybe the second one is the simplest and would easily allow to dig info in the proprietary header (eg. csa).
I will try to make these changes in a branch.

**Comment by satra** [comment]
@bpinsard - quick ping if you made any progress on this.

**Comment by bpinsard** [comment]
@satra see PR #333 
This is really basic but allow me to get information I needed.
