### ISSUE TITLE
Support pepolar fmaps

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#357]
Not yet sure if might be reproin heuristic specific. ATM for SE sequences intended to be pepolar fieldmaps https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-4-multiple-phase-encoded-directions-pepolar we are getting files with `_magnitude` suffix, whenever it should be `_epi`.

Attn @amanelis17

**Comment by pvelasco** [comment]
Hi @yarikoptic,

Yes, it looks like the problem is with the reproin heuristic file.  The pepolar fieldmaps are magnitude images, so they have the `M` label in the `s.image_type` and reproin will assign the `seqtype_label` `magnitude`.
What we do in [our heuristic file](https://github.com/cbinyu/heudiconv/blob/master/heudiconv/heuristics/cbi_heuristic.py) is we also check the `s.sequence_name`: `epse2d` is for the pepolar fieldmaps, while the traditional GRE fieldmaps `s.sequence_name` is `fm2d`.  (NB: This is for a Siemens Prisma)
So, I would do something like this:
```
if seqtype == 'fmap' and not seqtype_label:
    if 'fm2d' in s.sequence_name:
        if not dcm_image_iod_spec:
            raise ValueError("Do not know image data type yet to make decision")
        seqtype_label = {
            'M': 'magnitude',  # might want explicit {file_index}  ?
            'P': 'phasediff',
            'DIFFUSION': 'epi', # according to KODI those DWI are the EPIs we need
        }[dcm_image_iod_spec]
    else:
        seqtype_label = 'epi'     # (or whichever label you want to give it).
```

For other scanner vendors, you will need to check the `sequence_name` for the GRE fieldmaps and include them in the new `if` statement.

I hope this helps.

**Comment by yarikoptic** [comment]
THANK YOU @pvelasco !  I think in our (reproin) case we could judge based on having `_dir-` field present, which is defined/makes sense only for pepolar ones and not for generic fieldmaps
