### ISSUE TITLE
Kick out 0.6 release

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#392]
We amassed a good amount of changes and enhancements to progress minor release number, and we must release.

TODOs:
- [ ] prepare CHANGELOG (@mgxd are you around to help?)
- [x] do  a sample manual regression testing to compare behaviors with 0.5.4.  Anyone is welcome to HELP/report!  Reminder -- there is a `utils/test-compare-two-versions.sh` which could come handy

List of PRs merged is available from https://github.com/nipy/heudiconv/milestone/4?closed=1 ; I have moved many previously scheduled for 0.6 issues/PRs into a new 0.7 (e.g. the groupping PR).

**Comment by satra** [comment]
@yarikoptic @mgxd - do you want to include the et response system in this, as we have in nipype:

https://github.com/nipy/nipype/blob/master/nipype/__init__.py#L69

together with the .et file:

https://github.com/nipy/nipype/blob/master/.et

we have already used this in nipype since we released a couple of really do not use versions.

**Comment by mgxd** [comment]
yes, we should definitely

**Comment by yarikoptic** [comment]
cool idea on `bad_versions` and `.et`!
But IMHO, as suggested/discussed in https://github.com/ReproNim/reproman/pull/493, this whole `check_latest_version` (with necessary parametrizations) should be implemented within etelemetry itself, so downstream projects did not have to redo this templated code, each slightly differently and possibly less efficiently.
@mgxd , would you have time/interest to introduce it to etelemetry?
