### ISSUE TITLE
AttributeError: 'Dataset' object has no attribute 'add'

### ISSUE THREAD

**Issue by tsalo** [nipy/heudiconv#463]
### Summary

Datalad version 0.13.0 removed `datalad add`, which is what is used in `heudiconv`. 
Heudiconv's requirements include datalad >=0.12.3.

We could either require < 0.13.0 or update the datalad integration to support 0.13.0+.

### Platform details:

Choose one:
- [ ] Local environment

- [X] Container: Docker built on current master

- Heudiconv version: current master

**Comment by yarikoptic** [comment]
oh crap... thanks for spotting/reporting!  I will look into cooking up a quick bugfix PR.  We should just switch `.save`, it should already be good  in 0.12.3.  

Unfortunately pypi (or conda) does not have any means  to declare "Breaks" relationship (like debian allows) so we could state that datalad 0.13. broke heudiconv before upcoming now bugfix release. So AFAIK whatever we do now, since we cannot tune previous released versions, we just need to fix it up, and let people know that they would need to downgrade datalad if they need to use previous version

**Comment by yarikoptic** [comment]
may be to prevent such breakages in the future we should announce
```
datalad >=0.12.3, <0.14
```
and then boost it manually when we verify that "all is good".  It might complicate testing a bit (since pip might force older datalad) if I decide to add heudiconv to https://github.com/datalad/datalad-extensions/ to detect when we (in datalad) break api while affecting heudiconv, but that should be a separate issue
