### ISSUE TITLE
Question: Why is dcm2niix saving to /tmp

### ISSUE THREAD

**Issue by mirestrepo** [nipy/heudiconv#481]
### Summary

In our logs I can see that `dcm2niix` is saving to a random folder in `/tmp`. For instance I get messages like this one:
```
INFO: [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z y -x n -t n -m n -f func -o . -s n -v n /tmp/dcm2niix0odmo4o6/convert
```
If we isolate our containers from host, i.e, `--contain` flag in singularity, then the container `/tmp` may run out of memory to store all the nifti files. While we have ways to work around this, it took a while to figure out what was going on. Our `nii.gz` where just showing missing blocks. I think it is unexpected that heudiconv would be using  a hardcoded `/tmp` to temporarily store conversion.  Is there a way to change the path or make that assumption more clear to the user? 

### Platform details:

Choose one:
- [ ] Local environment

- [x] Container

This is a custom container 
https://hub.docker.com/repository/docker/brownbnc/xnat-tools
All versions contain the same version of heudiconv and dcm2nii
While we create a docker container we use it mostly as a singularity container from our HPC

- Heudiconv version: 

- heudiconv —version 0.6.0
- dcm2niiX version v1.0.20190902

**Comment by yarikoptic** [comment]
On one hand I am not sure if heudiconv should use any other directory as "temporary" unless explicitly instructed to do so.  But on the other -- large converted files might then end up on a different partition from the target one, so not only exhaust `/tmp` but also result in less efficient transfer to the target location (yet to check if we `cp` or `mv` here ;)).  So we might want to reconsider.

In either of those cases a workaround would be to pass/set environment variable `TMPDIR` for the run of the container to point to some location with sufficient storage/on the same file system (`-e TMPDIR=PATH` for docker? didn't try)
Note: Due to still open #462 care should be taken to ensure that the `TMPDIR` is not within target output directory, since it might pollute target output location.

**Comment by yarikoptic** [comment]
Oh, and on "why"  -- we "group" dicoms to be converted from a single series (source directory could have many series dumped into a single directory) and place into that temporary directory to pass to `dcm2niix`.

**Comment by mirestrepo** [comment]
I was just running `fmriprep` and was reminded that they have an input  `-w, --work-dir`, to set their working directory, which I think it serves the same purpose. Would it make sense for heudiconv to do the same?
