### ISSUE TITLE
Randomly not creating event.tsv placeholders

### ISSUE THREAD

**Issue by tessaclarkson** [nipy/heudiconv#498]
### Summary
 the conversion of all of the data for all subjects worked fine. the only issues was that for 4 of the 19 subjects pulled through the script the events.tsv placeholder files were not created. (this is not a big deal since we generate these later on, but I thought i would report in case it was a bug)

### Platform details:

Choose one:
- [ ] Local environment

- [ ] Container
 singularity

- Heudiconv version: 
 heudiconv_0.5.4

**Comment by yarikoptic** [comment]
Thanks for the report but I am not sure if it is "actionable" since not enough information provided (heuristic, logs, etc), and also current version of heudiconv is 0.9.0 .  If you have a chance to try that recent version  and it also produces no placeholders -- feel more than welcome to reopen (ideally with more information).
