### ISSUE TITLE
Can I output BIDS-style JSON sidecar files in a non-BIDS dataset?

### ISSUE THREAD

**Issue by hbraunDSP** [nipy/heudiconv#506]
### Summary

I would like to output BIDS-style *.json metadata files, but don't want any other BIDS features.  Is this possible?  I'm hoping it can be done through the `--dcmconfig` option but I can't find any documentation on how to use it.

### Platform details:

Choose one:
- [x] Local environment

- [ ] Container

CentOS Linux release 7.9.2009 (Core), Python 3.6.8 :: Anaconda custom (64-bit)

- Heudiconv version: 0.9.0

**Comment by yarikoptic** [comment]
I don't think it is possible ATM.  We do have `--bids ` option which already can take "notop" which would not create top level files.  May be someone could bolt on more of options to get to the bottom of achieving "sidecar-only" mode, but I think it might be "too deep" to be worthwhile torturing "bids mode" of operation. Overall -- if possible to achieve desired without major torture, PR is welcome, but otherwise it sounds like too niche of a use-case: I do not see why not to just convert to BIDS to start with.

**Comment by hbraunDSP** [comment]
OK.  All I needed was to call dcm2niix with the `-b y` option, and I was hoping there was a way to pass options directly to it.  You're right, this isn't worth adding. My problem was that I had to keep some existing subject IDs that contained underscores and BIDS mode was (correctly) removing them. 

For anyone else dealing with a similar problem: My workaround is to pass the unsanitized subject ID, session ID, and some other metadata to my heuristic file in environment variables. Not pretty, but it worked.

**Comment by yarikoptic** [comment]
might be of help -- you can point to a config file for dcm2niix:
```
$> heudiconv --help | grep -1 dcm2niix
                 [-d DICOM_DIR_TEMPLATE | --files [FILES ...]]
                 [-s [SUBJS ...]] [-c {dcm2niix,none}] [-o OUTDIR]
                 [-l LOCATOR] [-a CONV_OUTDIR] [--anon-cmd ANON_CMD]
--
                        IDs deduced by the heuristic.
  -c {dcm2niix,none}, --converter {dcm2niix,none}
                        Tool to use for DICOM conversion. Setting to "none"
--
  --dcmconfig DCMCONFIG
                        JSON file for additional dcm2niix configuration.
```
but I am not sure what you end up in terms of files naming at the end, i.e. either produced then sidecar files would be properly treated/renamed etc.
