### ISSUE TITLE
Some warnings and errors with heudiconv 0.11.6

### ISSUE THREAD

**Issue by bhgtii** [nipy/heudiconv#613]
### Summary

The data comes from a SIEMENS PRISMA FIT XA30 and consists of an mprage and dwi images.
The conversion works well just a little concerned because of the error and warning messages (please see below). Are they posing any issues for the conversion. We need the data in BIDS for qsiprep.

Thanks a lot for your advice,
Claudia

### Platform details:

Choose one:
- Local environment 
- macOS Monterey 12.6
- Terminal Version 2.12.7 (445) (bash shell)
- python version n.a.
- Container Docker Desktop Version 4.11.1 (84025)

- Heudiconv version: 0.11.6

1. WARNING: Failed to get date/time for the content: 'FileDataset' object has no attribute 'AcquisitionDate'
WARNING: Failed to find task field in /base/Nifti/sub-5258/ses-9720/anat/sub-5258_ses-9720_t1mpragesagp20.8iso.json.

2. 221201-11:19:07,902 nipype.workflow WARNING:

Storing result file without outputs
WARNING: Storing result file without outputs
221201-11:19:07,903 nipype.workflow WARNING:
[Node] Error on "embedder" (/tmp/embedmeta_kb39vw7/embedder)
WARNING: [Node] Error on "embedder" (/tmp/embedmeta_kb39vw7/embedder)
ERROR: Embedding failed: Exception raised while executing Node embedder.

3. File "/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/dcmstack/dcmmeta.py", line 306, in check_valid raise InvalidExtensionError('Missing required base '
dcmstack.dcmmeta.InvalidExtensionError: The extension is not valid: Missing required base classification time

**Comment by yarikoptic** [comment]
1.

1.a -- should get back to https://github.com/nipy/heudiconv/issues/537 and there on

1.b. `Failed to find task field` -- indeed useless now. Submitting PR which will close this issue since the other aspects IMHO are already known in other issues here or elsewhere

2. I think it is the result of 3? so see:

3. related issue here: https://github.com/nipy/heudiconv/issues/582, and I think you can avoid running into this at the cost of sacrificing extracting more metadata from dicoms using `--minmeta` flag.   But original issue was filed against dcmstack where I followed up inquiring: https://github.com/moloney/dcmstack/issues/71#issuecomment-1403986016  since most likely we just would need to fix that one over there
